quests:
    type:     rest
    resource: QuestServer\ApiBundle\Controller\QuestsController

questions:
    type:     rest
    parent:   quests
    resource: QuestServer\ApiBundle\Controller\QuestionsController