admin_question:
    pattern:  /quest/{questID}/question/
    defaults: { _controller: "QuestServerQuestBundle:Question:index" }

admin_question_new:
    pattern:  /quest/{questID}/question/new
    defaults: { _controller: "QuestServerQuestBundle:Question:new" }

admin_question_show:
    pattern:  /quest/{questID}/question/{id}
    defaults: { _controller: "QuestServerQuestBundle:Question:show" }

admin_question_create:
    pattern:  /quest/{questID}/question/create
    defaults: { _controller: "QuestServerQuestBundle:Question:create" }
    requirements: { _method: post }

admin_question_edit:
    pattern:  /quest/{questID}/question/{id}/edit
    defaults: { _controller: "QuestServerQuestBundle:Question:edit" }

admin_question_update:
    pattern:  /quest/{questID}/question/{id}/update
    defaults: { _controller: "QuestServerQuestBundle:Question:update" }
    requirements: { _method: post|put }

admin_question_delete:
    pattern:  /question/{id}/delete
    defaults: { _controller: "QuestServerQuestBundle:Question:delete" }
    requirements: { _method: post|delete }
