stud_io_tracker:
    resource: "@StudIOTrackerBundle/Resources/config/routing.yml"
    prefix:   /

quest_server_frontend:
    resource: "@QuestServerFrontendBundle/Resources/config/routing.yml"
    prefix:   /

quest_server_api:
    type: rest
    resource: "@QuestServerApiBundle/Resources/config/routing.yml"
    prefix:   /api

quest_server_quest:
    resource: "@QuestServerQuestBundle/Resources/config/routing.yml"
    prefix:   /

quest_server_common:
    resource: "@QuestServerCommonBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc