quest_server_quest:
    resource: "@QuestServerQuestBundle/Resources/config/routing.yml"
    prefix:   /

quest_server_common:
    resource: "@QuestServerCommonBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc