parameters:
#    quest_server_common.example.class: QuestServer\CommonBundle\Example

services:
#    quest_server_common.example:
#        class: %quest_server_common.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
