parameters:
#    quest_server_quest.example.class: QuestServer\QuestBundle\Example

services:
#    quest_server_quest.example:
#        class: %quest_server_quest.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
