parameters:
#    quest_server_frontend.example.class: QuestServer\FrontendBundle\Example

services:
#    quest_server_frontend.example:
#        class: %quest_server_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
