QuestServer\QuestBundle\Entity\Answer:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        value:
            type: string
            length: 255
    manyToOne:
        question:
          targetEntity: Question
          inversedBy: answers
          joinColumn:
            name: Question_id
            referencedColumnName: id
        user:
          targetEntity: QuestServer\CommonBundle\Entity\User
          inversedBy: answers
          joinColumn:
            name: user_id
            referencedColumnName: id
    lifecycleCallbacks: {  }
