QuestServer\QuestBundle\Entity\Quest:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
        validFrom:
            type: datetime
        validUntill:
            type: datetime
        allowResubmit:
            type:  boolean
            nullable: true
    oneToMany:
        questions:
          targetEntity: Question
          mappedBy: quest
    lifecycleCallbacks: {  }
